name: Azure Web App CI/CD

on:
  push:
    branches:
      - main  # Deploy on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js (adjust to your app's environment)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the application (if needed)
    - name: Build app
      run: npm run build  # Replace with your build command if needed

    # Step 5: Deploy to Azure Web App using the Azure Web App deploy action
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: team7-backend-app-unique-123  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Store your publish profile in GitHub secrets
        package: .  # Use the current directory, or specify the build directory if you have one
